# Generated by Django 3.2 on 2024-04-23 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kakeiboapp', '0002_record_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.ImageField(default=100, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.IntegerField(choices=[(0, '収入'), (1, '支出')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
